"""Collaudo della pagina a schede, in un browser vero con la porta finta.

    python3 collaudo/schede.py index.html
    CHROMIUM=/percorso/chrome python3 collaudo/schede.py index.html

Nessuna richiesta esce: pagina, conto.json, sostieni.json e porta sono
serviti da qui. Verde = 0 errori JavaScript e tutte le prove passate.
Nato il 26 settembre 2026 (Athena): era rosso sull'errore d'avvio che
avrebbe fermato la pagina a chi torna.
"""
import json, asyncio, sys, os
from playwright.async_api import async_playwright
PAGINA=open(sys.argv[1],encoding="utf-8").read()
PORTA="https://jjavis-porta.19-jjardito93.workers.dev"
BASE="https://jjoeboy93.github.io/JJA-VIS/"
inviati=[]
conta_risposte=[]
async def instrada(route):
    u=route.request.url
    if u.startswith(BASE) and (u==BASE or "#" in u or u.endswith("index.html")):
        return await route.fulfill(body=PAGINA, content_type="text/html")
    if u.endswith("conto.json"): return await route.fulfill(body=open(os.path.join(os.path.dirname(os.path.abspath(sys.argv[1])),"conto.json")).read(), content_type="application/json")
    if u.endswith("sostieni.json"): return await route.fulfill(body=json.dumps(SOST), content_type="application/json")
    if u.startswith(PORTA):
        if route.request.method=="POST":
            corpo=json.loads(route.request.post_data); inviati.append((u.split("/")[-1], corpo))
            if NOVA["acceso"] and u.endswith("/parla") and corpo.get("da_dove")=="chat":
                sub={"id":"abc12345-n","testo":"Posso prepararti uno strumento per le interrogazioni.","azione":{"servizio":"commissione","tipo":"Strumento web","bozza":"Uno strumento per preparare le interrogazioni"},"passa":False}
                return await route.fulfill(status=201, body=json.dumps({"ok":True,"id":"abc12345","subito":sub}), content_type="application/json", headers={"Access-Control-Allow-Origin":"https://jjoeboy93.github.io"})
            return await route.fulfill(status=201, body='{"ok":true,"id":"abc12345"}', content_type="application/json", headers={"Access-Control-Allow-Origin":"https://jjoeboy93.github.io"})
        if u.endswith("/nova"): return await route.fulfill(body=json.dumps({"acceso":NOVA["acceso"]}), content_type="application/json")
        if u.endswith("/vetrina"): return await route.fulfill(body='{"canzoni":5747,"attrezzi":41}', content_type="application/json")
        if "/risposte" in u:
            conta_risposte.append(1)
            return await route.fulfill(body=json.dumps({"risposte":RISPOSTE}), content_type="application/json")
        return await route.fulfill(body='[]', content_type="application/json")
    await route.fulfill(status=404, body="")
SOST={"pronto":False,"modi":[]}
NOVA={"acceso":False}
RISPOSTE=[]
def ok(c,m):
    print(("  ✅ " if c else "  ❌ ")+m); 
    if not c: ok.errori+=1
ok.errori=0
async def main():
    global SOST
    async with async_playwright() as p:
        b=await p.chromium.launch(executable_path=os.environ.get("CHROMIUM") or None)
        ctx=await b.new_context(viewport={"width":390,"height":844}, has_touch=True, is_mobile=True)
        await ctx.route("**/*", instrada)
        pg=await ctx.new_page(); errori=[]
        pg.on("pageerror", lambda e: errori.append(str(e)))
        print("── primo arrivo")
        await pg.goto(BASE); await pg.wait_for_timeout(400)
        ok(await pg.is_visible("#o1"), "si apre su Inizia, «Come vuoi chiamarmi?»")
        ok(await pg.inner_text("#et-inizia")=="Inizia", "la prima scheda si chiama Inizia")
        ok(not await pg.is_visible("#p-chi-sono"), "le altre schede sono chiuse")
        await pg.click("#s-chi-sono"); await pg.wait_for_timeout(300)
        ok(await pg.is_visible("#tcs") and "#chi-sono" in pg.url, "tocco «Chi sono»: pannello e indirizzo")
        testo_chi=await pg.inner_text("#p-chi-sono")
        ok("Non rispondo: anticipo" in testo_chi and "Imparo te" in testo_chi and "Per chiunque" in testo_chi and not await pg.evaluate("!!document.querySelector('#p-chi-sono #tf')"), "Chi sono parla di chi è JJA-VIS; l'elenco di cosa so fare non c'è più (JJ, 29/9)")
        ok(not any(p in testo_chi for p in ["Albero","JARVIS privato","Stark","archetip"]), "dal blueprint solo quello che si può dire in pubblico")
        ok(testo_chi.count("Chi mi costruisce")==1 and testo_chi.count("corriere")<=2, "«Da dove nasco» non si ripete (JJ, 29/9)")
        await pg.click("#s-sa-fare"); await pg.wait_for_timeout(300)
        ok(await pg.is_visible("#tf") and "#sa-fare" in pg.url, "«Cosa so fare» è una scheda sua")
        ok(await pg.inner_text("#n-canzoni")=="5.747", "i numeri della vetrina arrivano")
        await pg.click("#s-chi-sono"); await pg.wait_for_timeout(300)
        ok(not await pg.evaluate("!!document.querySelector('#p-chi-sono #conto')"), "Quanto costo non è più in Chi sono")
        ok(await pg.inner_text("#prova")=="Comincia", "Provami dice Comincia, senza nome")
        await pg.click("#s-profilo"); await pg.wait_for_timeout(200)
        ok(await pg.is_visible("#profilo-vuoto") and not await pg.is_visible("#profilo-nome"), "profilo senza nome: manda a Inizia")
        await pg.click('#temi-profilo [data-tema="naturale"]')
        ok(await pg.evaluate("document.documentElement.dataset.tema")=="naturale", "il tema cambia dal profilo")
        await pg.click("#s-sostieni"); await pg.wait_for_timeout(200)
        ok(await pg.is_visible("#sostieni-presto") and await pg.inner_html("#sostieni-modi")=="", "sostieni senza link: nessun pulsante finto")
        print("── il dito")
        await pg.click("#s-inizia"); await pg.wait_for_timeout(200)
        async def scorri(dx):
            await pg.evaluate("""dx=>{const m=document.querySelector('main');const T=(x,y)=>new Touch({identifier:1,target:m,clientX:x,clientY:y});
              m.dispatchEvent(new TouchEvent('touchstart',{touches:[T(300,400)],changedTouches:[T(300,400)],bubbles:true}));
              m.dispatchEvent(new TouchEvent('touchend',{touches:[],changedTouches:[T(300+dx,410)],bubbles:true}));}""", dx)
            await pg.wait_for_timeout(250)
        await scorri(-150); ok(await pg.evaluate("document.body.dataset.scheda")=="chi-sono", "a sinistra: Chi sono")
        await scorri(-150); ok(await pg.evaluate("document.body.dataset.scheda")=="sa-fare", "ancora: Cosa so fare")
        await scorri(150); ok(await pg.evaluate("document.body.dataset.scheda")=="chi-sono", "a destra: torna")
        await scorri(-30); ok(await pg.evaluate("document.body.dataset.scheda")=="chi-sono", "un tocco corto non cambia scheda")
        await pg.click("#s-inizia"); await scorri(150); ok(await pg.evaluate("document.body.dataset.scheda")=="inizia", "dalla prima non si va oltre")
        print("── la prima conversazione")
        await pg.click('#nomi .scelta:has-text("Atlas")'); await pg.click("#avanti-o1"); await pg.wait_for_timeout(300)
        await pg.click("#avanti-o2"); await pg.fill("#tuo-nome","Marco"); await pg.click("#avanti-o3"); await pg.wait_for_timeout(3200)
        ok(await pg.inner_text("#et-inizia")=="Atlas", "la scheda prende il nome dato: Atlas")
        ok(await pg.is_visible("#d1") and not await pg.is_visible("#parla"), "sotto il benvenuto le domande; la chat arriva a questionario finito (JJ, 29/9)")
        await pg.click('#d1 .scelta:has-text("Corriere")'); await pg.wait_for_timeout(200)
        await pg.click('#salto-cosa'); await pg.wait_for_timeout(300)
        ok(await pg.evaluate("document.body.dataset.scheda")=="sa-fare", "«Cosa so fare →» porta a Cosa so fare, non più a Chi sono")
        await pg.click("#s-chi-sono"); await pg.wait_for_timeout(300)
        ok(await pg.inner_text("#prova")=="Parla con Atlas", "Provami adesso dice Parla con Atlas")
        await pg.click("#s-profilo"); await pg.wait_for_timeout(200)
        so=await pg.inner_text("#so-di-te")
        ok("Marco" in so and "Corriere" in so, "Cosa so di te: nome e mestiere")
        ok(await pg.input_value("#nuova-sigla")=="Atlas", "il nome nel campo del profilo")
        await pg.fill("#nuova-sigla","Iris"); await pg.click("#cambia-nome")
        ok(await pg.inner_text("#nome-testata")=="Iris" and await pg.inner_text("#et-inizia")=="Iris", "cambio nome: testata e scheda")
        print("── investitori")
        await pg.click("#s-investitori"); await pg.wait_for_timeout(200)
        ok(await pg.is_disabled("#inv-manda"), "Manda spento finché mancano i campi")
        await pg.click('#inv-interesse .scelta:has-text("Investire")'); await pg.fill("#inv-nome","Anna Rossi"); await pg.fill("#inv-mail","anna@esempio")
        await pg.click("#inv-manda"); ok("mail" in (await pg.inner_text("#inv-esito")), "mail incompleta: lo dice")
        await pg.fill("#inv-mail","anna@esempio.it"); await pg.click("#inv-manda")
        ok("spunta" in (await pg.inner_text("#inv-esito")), "senza consenso non parte")
        await pg.check("#inv-ok"); await pg.fill("#inv-messaggio","Vorrei il dossier."); await pg.click("#inv-manda"); await pg.wait_for_timeout(300)
        inv=[d for (r,d) in inviati if r=="parla"]
        ok(len(inv)==1 and inv[0]["da_dove"]=="investitori", "parte su /parla con da_dove investitori")
        if inv: print("     testo:", json.dumps(inv[0]["testo"], ensure_ascii=False))
        ok(inv and "anna@" not in inv[0]["testo"] and "Anna" not in inv[0]["testo"], "nome e mail NON nel testo (va all'IA)")
        ok(inv and inv[0].get("contatto",{}).get("mail")=="anna@esempio.it" and inv[0]["contatto"].get("consenso") is True, "nome e mail viaggiano in «contatto», con consenso")
        t=await pg.inner_text("#inv-esito"); print("     esito:",t); ok("Arrivato" in t, "dice Arrivato")
        print("── costruiscimi qualcosa")
        await pg.click("#s-bottega"); await pg.wait_for_timeout(200)
        ok(await pg.is_visible("#costruisci") and await pg.is_visible("#clio") and await pg.is_visible("#sopralluogo"), "Clio, Sopralluogo e commissioni sono nella Bottega")
        ok(not await pg.evaluate("!!document.querySelector('#p-chi-sono #costruisci, #p-chi-sono #clio, #p-chi-sono #sopralluogo')"), "e non più in Chi sono")
        await pg.click('#cm-cosa .scelta:has-text("Sito")'); await pg.fill("#cm-descrizione","Il sito della pizzeria col menù")
        await pg.fill("#cm-mail","luca@pizzeria.it"); await pg.fill("#cm-nome","Luca")
        await pg.click("#cm-manda"); ok("spunta" in await pg.inner_text("#cm-esito"), "senza consenso non parte")
        await pg.check("#cm-ok"); await pg.click("#cm-manda"); await pg.wait_for_timeout(300)
        cm=[d for (r,d) in inviati if r=="parla" and d.get("da_dove")=="commissione"]
        ok(len(cm)==1 and cm[0]["testo"].startswith("🛠 Sito o pagina web — ") and "luca@" not in cm[0]["testo"], "parte come commissione, senza mail nel testo")
        ok(cm and cm[0]["contatto"]["mail"]=="luca@pizzeria.it", "la mail nel contatto")
        ok("preventivo" in await pg.inner_text("#cm-esito"), "dice che il preventivo arriva per mail")
        print("── chi torna (il caso che si rompeva)")
        e_prima=len(errori)
        pg2=await ctx.new_page(); pg2.on("pageerror", lambda e: errori.append(str(e)))
        await pg2.goto(BASE+"#investitori"); await pg2.wait_for_timeout(400)
        ok(len(errori)==e_prima, "nessun errore all'avvio con un nome già salvato")
        ok(await pg2.evaluate("document.body.dataset.scheda")=="investitori", "un link a #investitori apre quella scheda")
        ok(await pg2.inner_text("#et-inizia")=="Iris", "ritrova il nome")
        await pg2.goto(BASE+"#dati"); await pg2.wait_for_timeout(300)
        ok(await pg2.evaluate("document.body.dataset.scheda")=="profilo", "#dati apre il profilo, dov'è l'informativa")
        print("── sostieni con un link vero")
        SOST={"pronto":True,"modi":[{"nome":"Offrimi un caffè","url":"https://ko-fi.com/esempio"}]}
        await pg2.goto(BASE+"#sostieni"); await pg2.reload(); await pg2.wait_for_timeout(400)
        ok("Offrimi un caffè" in await pg2.inner_text("#sostieni-modi"), "col link compare il pulsante")
        print("── la prima scheda, al ritorno")
        await pg2.goto(BASE+"#inizia"); await pg2.wait_for_timeout(300)
        ok(await pg2.locator("#benvenuto #ricomincia").count()==0 and "Ricomincia" not in await pg2.inner_text("#benvenuto"), "niente «Ricomincia» nella prima scheda")
        ok(await pg2.locator('#benvenuto a[href="#profilo"]').count()==1, "rimanda al Profilo")
        print("── le domande del ritorno, in fila")
        pg3=await ctx.new_page(); pg3.on("pageerror", lambda e: errori.append(str(e)))
        await pg3.add_init_script("localStorage.setItem('jjavis-io', JSON.stringify({id:'a1b2c3d4e5f60718',nome:'Nova',tema:'deciso',tuo:'Jacopo',inviato:true,mestiere:'Corriere o autista',tempo:'Preventivi, conti, fatture'}))")
        await pg3.goto(BASE); await pg3.wait_for_timeout(300)
        d1=await pg3.evaluate("document.getElementById('conosci-domanda').textContent"); ok("ora comincia" in d1, "prima domanda: "+d1)
        await pg3.click('#conosci-scelte .scelta:has-text("Cambia ogni giorno")'); await pg3.wait_for_timeout(1200)
        d2=await pg3.evaluate("document.getElementById('conosci-domanda').textContent"); ok(d2!=d1 and d2, "dopo un secondo, senza ricaricare: "+d2)
        for _ in range(8):
            if not await pg3.is_visible("#conosci-scelte .scelta:not([disabled])"): break
            await pg3.click("#conosci-scelte .scelta:not([disabled]) >> nth=0"); await pg3.wait_for_timeout(1100)
        ok(await pg3.is_visible("#conosci-fine") and not await pg3.is_visible("#conosci"), "finite le domande: «di te so già parecchio»")
        await pg3.close()
        print("── le risposte arrivano da sole")
        pg4=await ctx.new_page(); pg4.on("pageerror", lambda e: errori.append(str(e)))
        await pg4.clock.install()
        await pg4.add_init_script("localStorage.setItem('jjavis-io', JSON.stringify({id:'a1b2c3d4e5f60718',nome:'Nova',inviato:true,mestiere:'Ufficio'}))")
        await pg4.goto(BASE+"#parla"); await pg4.wait_for_timeout(300)
        await pg4.fill("#scrivi","Mi faresti il sito della mia azienda?"); await pg4.click("#manda-chat"); await pg4.wait_for_timeout(300)
        prima=len(conta_risposte)
        await pg4.click("#s-chi-sono")
        RISPOSTE.append({"id":"abc12345","domanda":"Mi faresti il sito della mia azienda?","risposta":"Sì, si può fare: lasciami la mail.","quando":"2026-09-26T10:00:00Z"})
        await pg4.clock.fast_forward(21000); await pg4.wait_for_timeout(400)
        ok(len(conta_risposte)>prima, "dopo 20 secondi chiede da sola")
        ok("si può fare" in await pg4.inner_text("#chat"), "la risposta è nella chat senza ricaricare")
        ok(await pg4.evaluate("document.getElementById('s-inizia').classList.contains('nuovo')"), "il puntino sulla prima scheda, perché sei altrove")
        await pg4.click("#s-inizia"); await pg4.wait_for_timeout(200)
        ok(not await pg4.evaluate("document.getElementById('s-inizia').classList.contains('nuovo')"), "tornando, il puntino si spegne")
        dopo=len(conta_risposte); await pg4.clock.fast_forward(180000); await pg4.wait_for_timeout(300)
        ok(len(conta_risposte)==dopo, "niente più in attesa: smette di chiedere")
        RISPOSTE.clear(); await pg4.close()
        print("── Clio, per le guide")
        pg5=await ctx.new_page(); pg5.on("pageerror", lambda e: errori.append(str(e)))
        await pg5.add_init_script("localStorage.setItem('jjavis-io', JSON.stringify({id:'b1b2c3d4e5f60718',nome:'Nova'}))")
        await pg5.goto(BASE+"#clio"); await pg5.wait_for_timeout(300)
        ok(await pg5.evaluate("document.body.dataset.scheda")=="bottega" and await pg5.is_visible("#cl-manda"), "#clio apre la Bottega sulla sezione Clio")
        await pg5.fill("#cl-lingue","italiano, inglese"); await pg5.fill("#cl-mail","giulia@guide.it"); await pg5.fill("#cl-nome","Giulia")
        await pg5.click("#cl-manda"); ok("spunta" in await pg5.inner_text("#cl-esito"), "senza consenso non parte")
        await pg5.check("#cl-ok"); await pg5.click("#cl-manda"); await pg5.wait_for_timeout(300)
        cl=[d for (r,d) in inviati if r=="parla" and d.get("da_dove")=="clio"]
        ok(len(cl)==1 and cl[0]["testo"].startswith("🏛 Clio — lingue: italiano, inglese") and "giulia@" not in cl[0]["testo"] and cl[0]["contatto"]["mail"]=="giulia@guide.it", "parte come clio, mail nel contatto e non nel testo")
        ok("invito" in await pg5.inner_text("#cl-esito"), "dice che l'invito arriva per mail")
        await pg5.goto(BASE+"#d1"); await pg5.wait_for_timeout(200)
        await pg5.click('#d1 .scelta:has-text("Guida turistica")'); await pg5.wait_for_timeout(200)
        ok(await pg5.locator('#r1 a[href="#clio"]').count()==1, "chi sceglie Guida turistica si sente dire di Clio, col link")
        ok("Ripetere lo stesso tour" in await pg5.inner_text('.scelte[data-campo="tempo"]'), "e le domande dopo sono da guida")
        await pg5.close()
        print("── sopralluogo")
        pg6=await ctx.new_page(); pg6.on("pageerror", lambda e: errori.append(str(e)))
        await pg6.goto(BASE+"#sopralluogo"); await pg6.wait_for_timeout(300)
        ok(await pg6.evaluate("document.body.dataset.scheda")=="bottega" and await pg6.is_visible("#so-manda"), "#sopralluogo apre la Bottega sulla sezione")
        await pg6.click('#so-cosa .scelta:has-text("La mia attività")'); await pg6.fill("#so-link","pizzeria"); await pg6.fill("#so-mail","luca@pizzeria.it")
        await pg6.click("#so-manda"); ok("link" in await pg6.inner_text("#so-esito"), "un link senza punto: lo dice")
        await pg6.fill("#so-link","pizzeriadaluca.it"); await pg6.click("#so-manda")
        ok("spunta" in await pg6.inner_text("#so-esito"), "senza consenso non parte")
        await pg6.check("#so-ok"); await pg6.fill("#so-note","il menù non si trova"); await pg6.click("#so-manda"); await pg6.wait_for_timeout(300)
        so=[d for (r,d) in inviati if r=="parla" and d.get("da_dove")=="sopralluogo"]
        ok(len(so)==1 and so[0]["link"]=="https://pizzeriadaluca.it/" or (so and so[0]["link"]=="https://pizzeriadaluca.it"), "il link parte a parte, con https:// aggiunto")
        ok(so and so[0]["testo"].startswith("🔎 La mia attività: https://pizzeriadaluca.it") and "luca@" not in so[0]["testo"] and so[0]["contatto"]["mail"]=="luca@pizzeria.it", "testo col link, mail solo nel contatto")
        ok("per mail" in await pg6.inner_text("#so-esito"), "dice che arriva per mail")
        await pg6.close()
        await pg2.goto(BASE+"#bottega"); await pg2.wait_for_timeout(200)
        ok(await pg2.evaluate("document.body.dataset.scheda")=="bottega", "#bottega apre la Bottega")
        larghe=await pg2.evaluate("[...document.querySelectorAll('.schede .et')].filter(e=>e.scrollWidth>e.clientWidth+1).map(e=>e.textContent)")
        ok(larghe==[] or larghe==["Iris"], "le sei etichette ci stanno a 390 px: "+(",".join(larghe) or "tutte intere"))
        print("── una sola chat nella prima scheda")
        pg9=await b.new_page(viewport={"width":390,"height":844}, has_touch=True, is_mobile=True)
        await pg9.route("**/*", instrada); pg9.on("pageerror", lambda e: errori.append(str(e)))
        await pg9.add_init_script("localStorage.setItem('jjavis-io', JSON.stringify({id:'d1b2c3d4e5f60718',nome:'Nova',tuo:'Jacopo',inviato:true,mestiere:'Ufficio',mail:'jacopo@esempio.it'}))")
        await pg9.goto(BASE+"#inizia"); await pg9.wait_for_timeout(300)
        scrivibili=await pg9.evaluate("[...document.querySelectorAll('#p-inizia textarea')].filter(t=>t.offsetParent!==null).map(t=>t.id)")
        ok(scrivibili==["scrivi"], "chi torna ha un posto solo dove scrivere: "+",".join(scrivibili))
        ok(not await pg9.is_visible("#d4") and "scrivermi ancora" not in await pg9.inner_text("#p-inizia"), "«Vuoi scrivermi ancora?» non c'è più")
        await pg9.fill("#scrivi","Mi rispondi per mail?"); await pg9.click("#manda-chat"); await pg9.wait_for_timeout(300)
        ch=[d for (r,d) in inviati if r=="parla" and d.get("testo")=="Mi rispondi per mail?"]
        ok(ch and ch[0].get("contatto",{}).get("mail")=="jacopo@esempio.it" and "jacopo@" not in ch[0]["testo"], "con la mail salvata, la chat la manda nel contatto: la risposta arriva anche lì")
        ok("per mail" in await pg9.inner_text("#esito-chat"), "e lo dice")
        print("── la mail dal Profilo")
        await pg9.goto(BASE+"#profilo"); await pg9.wait_for_timeout(300)
        ok(await pg9.input_value("#profilo-mail")=="jacopo@esempio.it", "il Profilo mostra la mail")
        await pg9.fill("#profilo-mail",""); await pg9.click("#salva-mail")
        ok(not await pg9.evaluate("JSON.parse(localStorage.getItem('jjavis-io')).mail"), "svuotata e salvata: tolta")
        await pg9.fill("#profilo-mail","nuova@esempio.it"); await pg9.click("#salva-mail")
        ok("spunta" in await pg9.inner_text("#esito-profilo"), "senza consenso non si salva")
        await pg9.check("#profilo-mail-ok"); await pg9.click("#salva-mail")
        ok(await pg9.evaluate("JSON.parse(localStorage.getItem('jjavis-io')).mail")=="nuova@esempio.it", "con la spunta sì")
        print("── Numeri")
        await pg9.goto(BASE+"#numeri"); await pg9.wait_for_timeout(300)
        ok(await pg9.evaluate("document.body.dataset.scheda")=="numeri" and await pg9.is_visible("#conto") and await pg9.is_visible("#numeri-problema .numeri"), "Numeri: Quanto costo e il problema in numeri")
        ok(not await pg9.evaluate("!!document.querySelector('#p-investitori .numeri')") and await pg9.locator('#p-investitori a[href="#numeri-problema"]').count()==1, "Investi non ha più i numeri e rimanda lì")
        await pg9.goto(BASE+"#conto"); await pg9.wait_for_timeout(300)
        ok(await pg9.evaluate("document.body.dataset.scheda")=="numeri", "i vecchi link a #conto aprono Numeri")
        await pg9.close()
        print("── la prima volta")
        pga=await b.new_page(viewport={"width":390,"height":844}); await pga.route("**/*", instrada)
        await pga.goto(BASE); await pga.wait_for_timeout(200)
        ok(await pga.locator("#messaggio").count()==0 and "Manda le risposte" in await pga.inner_text("#d4"), "l'ultimo passo del sondaggio non ha più il campo messaggio")
        await pga.close()
        print("── la barra scorre")
        pg7=await b.new_page(viewport={"width":320,"height":700}, has_touch=True, is_mobile=True)
        await pg7.route("**/*", instrada); pg7.on("pageerror", lambda e: errori.append(str(e)))
        await pg7.add_init_script("localStorage.setItem('jjavis-io', JSON.stringify({id:'c1b2c3d4e5f60718',nome:'Nova',inviato:true}))")
        await pg7.goto(BASE+"#inizia"); await pg7.wait_for_timeout(300)
        m=await pg7.evaluate("(()=>{const c=document.querySelector('.schede');return {sw:c.scrollWidth,cw:c.clientWidth,min:Math.min(...[...c.children].map(b=>b.getBoundingClientRect().width)),tagliate:[...document.querySelectorAll('.schede .et')].filter(e=>e.scrollWidth>e.clientWidth+1).length,pagina:document.documentElement.scrollWidth}})()")
        ok(m["sw"]>m["cw"], f"a 320 px la barra scorre ({m['sw']} su {m['cw']} px)")
        ok(m["min"]>=74 and m["tagliate"]==0, f"nessuna scheda schiacciata: la più stretta {m['min']:.0f} px, etichette intere")
        ok(m["pagina"]<=320, "la pagina non scorre di lato")
        ok(await pg7.evaluate("document.querySelector('.schede').classList.contains('piu-dx')"), "la sfumatura a destra dice che ce ne sono altre")
        await pg7.goto(BASE+"#sostieni"); await pg7.wait_for_timeout(60)
        ok(await pg7.evaluate("document.documentElement.scrollWidth")<=320, "anche mentre il pannello entra, la pagina non si allarga")
        await pg7.wait_for_timeout(640)
        r=await pg7.evaluate("(()=>{const b=document.getElementById('s-sostieni').getBoundingClientRect();return [b.left,b.right]})()")
        ok(r[0]>=0 and r[1]<=321, f"aprendo Sostieni, la sua scheda si porta in vista ({r[0]:.0f}–{r[1]:.0f} px)")
        await pg7.close()
        pg8=await b.new_page(viewport={"width":800,"height":700})
        await pg8.route("**/*", instrada); await pg8.goto(BASE); await pg8.wait_for_timeout(300)
        c=await pg8.evaluate("(()=>{const c=document.querySelector('.schede');const a=c.firstElementChild.getBoundingClientRect().left, z=c.clientWidth-c.lastElementChild.getBoundingClientRect().right;return [c.scrollWidth<=c.clientWidth, Math.abs(a-z)<2]})()")
        ok(c[0] and c[1], "su uno schermo largo non scorre e resta centrata")
        await pg8.close()
        print("── Creator o gamer")
        await pg2.goto(BASE+"#d1"); await pg2.wait_for_timeout(200)
        ok(await pg2.locator('#d1 .scelta:has-text("Creator o gamer")').count()==1, "c'è il mestiere Creator o gamer")
        print("── la testata di JARVIS (29 settembre)")
        pg2=await ctx.new_page(); pg2.on("pageerror", lambda e: errori.append(str(e)))
        await pg2.goto(BASE); await pg2.evaluate("localStorage.clear()"); await pg2.reload(); await pg2.wait_for_timeout(300)
        ok(await pg2.evaluate("getComputedStyle(document.querySelector('.testa')).position")!="fixed", "senza nome il globo resta grande al centro, non fisso")
        await pg2.evaluate("localStorage.setItem(CHIAVE, JSON.stringify({nome:'Nova',tema:'tech',id:'x1'}))")
        for sch in ["inizia","bottega","numeri","investitori"]:
            await pg2.goto(BASE+"#"+sch); await pg2.reload(); await pg2.wait_for_timeout(300)
            await pg2.mouse.wheel(0,1200); await pg2.wait_for_timeout(200)
            t=await pg2.evaluate("(()=>{const r=document.querySelector('.testa').getBoundingClientRect(),g=document.querySelector('#globo').getBoundingClientRect();return {pos:getComputedStyle(document.querySelector('.testa')).position,top:r.top,gx:g.left,nome:document.querySelector('#nome-testata').textContent,sotto:document.querySelector('#sotto-testata').textContent}})()")
            ok(t["pos"]=="fixed" and t["top"]<=1 and t["gx"]<40 and t["nome"]=="Nova" and t["sotto"]=="il tuo JJA-VIS", f"{sch}: testata fissa in alto anche scorrendo, globo a sinistra, «Nova» e «il tuo JJA-VIS»")
        coperto=await pg2.evaluate("(()=>{window.scrollTo(0,0);const t=document.querySelector('.testa').getBoundingClientRect().bottom;const p=document.querySelector('.pannello.attivo .etichetta');return p.getBoundingClientRect().top<t})()")
        ok(not coperto, "la testata non copre il primo pannello")
        print("── Nova è una chat, come JARVIS (29 settembre)")
        await pg2.evaluate("localStorage.setItem(CHIAVE, JSON.stringify({nome:'Nova',tema:'tech',id:'x1',tuo:'Jacopo',inviato:true,mestiere:'Corriere o autista',tempo:'Preventivi, conti, fatture',chat:[{ruolo:'tu',testo:'Come mi potresti aiutare?'},{ruolo:'io',testo:'Ultima risposta di prova',nuovo:true}]}))")
        await pg2.goto(BASE+"#inizia"); await pg2.reload(); await pg2.wait_for_timeout(700)
        c=await pg2.evaluate("""(()=>{const b=document.querySelector('#barra-chat').getBoundingClientRect(), n=document.querySelector('.schede').getBoundingClientRect();
          const bolle=[...document.querySelectorAll('#chat .bolla')], u=bolle[bolle.length-1].getBoundingClientRect();
          return {pos:getComputedStyle(document.querySelector('#barra-chat')).position, sopra:Math.abs(b.bottom-n.top)<=1,
            titolo:document.querySelector('#tp').getBoundingClientRect().height>2, ultima:u.bottom<=b.top+1 && u.top>=0,
            spiega:getComputedStyle(document.querySelector('.spiega-chat')).display!=='none'}})()""")
        ok(c["pos"]=="fixed" and c["sopra"], "la casella è fissa in basso, appoggiata sopra le schede")
        ok(not c["titolo"], "niente titolo «Parla con»: la chat è la pagina")
        ordine=await pg2.evaluate("""(()=>{const y=id=>document.getElementById(id).getBoundingClientRect().top;
          return y('saluto')<y('ricordo') && y('ricordo')<y('salto-cosa') && y('salto-cosa')<y('saluto2')})()""")
        ok(ordine, "chi torna: saluto, poi «Mi ricordo di te», poi «Cosa so fare →», poi il resto")
        ok(c["ultima"], "aprendo Nova si vede l'ultimo messaggio, sopra la casella")
        ok(c["spiega"], "resta la frase onesta: le risposte non sono automatiche")
        await pg2.goto(BASE+"#bottega"); await pg2.wait_for_timeout(300)
        ok(not await pg2.is_visible("#barra-chat"), "sulle altre schede la casella non c'è")
        vede_=lambda sel: pg2.is_visible(sel)
        print("── Nova risponde subito e porta alla Bottega (2 ottobre)")
        NOVA["acceso"]=True
        await pg2.evaluate("localStorage.setItem(CHIAVE, JSON.stringify({nome:'Nova',tema:'tech',id:'abcdef0123456789',inviato:true,mestiere:'Altro',tempo:'Altro lavoro ripetitivo'}))")
        await pg2.goto(BASE+"#inizia"); await pg2.reload(); await pg2.wait_for_timeout(600)
        ok("Ti rispondo subito" in await pg2.inner_text("#spiega-chat") and "Non rispondo in automatico" not in await pg2.inner_text("#spiega-chat"), "con Nova accesa la frase sotto la chat dice la cosa vera")
        await pg2.fill("#scrivi","Sono un insegnante e perdo tempo con le interrogazioni"); await pg2.click("#manda-chat"); await pg2.wait_for_timeout(600)
        bolle=await pg2.evaluate("[...document.querySelectorAll('#chat .bolla')].map(b=>b.className+'|'+b.innerText)")
        ok(any("io|Posso prepararti" in b for b in bolle) and not any("appena posso" in b for b in bolle), "la risposta arriva subito, niente «ti rispondo appena posso»")
        await pg2.click("#chat .azione"); await pg2.wait_for_timeout(500)
        ok(await pg2.evaluate("document.body.dataset.scheda")=="bottega" and await pg2.input_value("#cm-descrizione")=="Uno strumento per preparare le interrogazioni"
           and await pg2.evaluate("[...document.querySelectorAll('#cm-cosa .scelta')].find(x=>x.getAttribute('aria-pressed')==='true').textContent.trim()")=="Strumento web",
           "il pulsante apre la Bottega su «Costruiscimi qualcosa», col tipo scelto e la richiesta già scritta")
        await pg2.reload(); await pg2.wait_for_timeout(500)
        # 2/10, JJ: letta e rientrato, la chat è pulita; la conversazione va nelle precedenti, col suo pulsante
        ok(await pg2.evaluate("document.querySelectorAll('#chat .bolla').length")==0 and await pg2.evaluate("document.querySelectorAll('#vecchie-elenco .azione').length")==1,
           "ricaricando, la chat è pulita e la risposta col pulsante è nelle conversazioni precedenti")
        NOVA["acceso"]=False
        await pg2.goto(BASE+"#inizia"); await pg2.reload(); await pg2.wait_for_timeout(500)
        ok("Non rispondo in automatico" in await pg2.inner_text("#spiega-chat"), "con Nova spenta resta la frase di prima")
        print("── finite le domande del giorno, la frase se ne va (29 settembre)")
        await pg2.evaluate("(()=>{const c={};CONOSCERTI.slice(0,-1).forEach(q=>c[q.k]='x');localStorage.setItem(CHIAVE, JSON.stringify({nome:'Nova',tema:'tech',id:'x1',inviato:true,mestiere:'Creator o gamer',tempo:'Trovare idee per i contenuti',conosciute:c}))})()")
        await pg2.goto(BASE+"#inizia"); await pg2.reload(); await pg2.wait_for_timeout(600)
        ok("Oggi voglio sapere una cosa in più" in await pg2.inner_text("#saluto2"), "con una domanda ancora da fare, Nova dice «Oggi voglio sapere una cosa in più»")
        await pg2.click("#conosci-scelte .scelta >> nth=0"); await pg2.wait_for_timeout(1300)
        ok("Oggi voglio sapere" not in await pg2.inner_text("#saluto2") and await vede_("#conosci-fine"), "risposta l'ultima, la frase sparisce subito, senza ricaricare")
        print("── i passi fatti se ne vanno (29 settembre)")
        await pg2.evaluate("localStorage.clear()"); await pg2.goto(BASE+"#inizia"); await pg2.reload(); await pg2.wait_for_timeout(400)
        vede=lambda sel: pg2.is_visible(sel)
        await pg2.click("#nomi .scelta >> text=Nova"); await pg2.click("#avanti-o1"); await pg2.wait_for_timeout(250)
        grande=await pg2.evaluate("getComputedStyle(document.querySelector('.testa')).position!=='fixed' && document.querySelector('#globo').getBoundingClientRect().width>90 && Math.abs(document.querySelector('#globo').getBoundingClientRect().left+document.querySelector('#globo').getBoundingClientRect().width/2-innerWidth/2)<4")
        ok(grande, "scelto il nome, la sfera resta grande al centro: si fa piccola solo col saluto")
        await pg2.reload(); await pg2.wait_for_timeout(500)
        ok(await vede("#o2") and not await vede("#benvenuto") and not await vede("#o1"), "ricaricato dopo il nome: si riparte da «Come mi vuoi vedere?», non si salta")
        await pg2.click("#avanti-o2"); await pg2.wait_for_timeout(250)
        await pg2.reload(); await pg2.wait_for_timeout(500)
        ok(await vede("#o3") and not await vede("#benvenuto"), "ricaricato dopo il colore: si riparte da «E tu come ti chiami?»")
        await pg2.fill("#tuo-nome","Jacopo"); await pg2.click("#avanti-o3"); await pg2.wait_for_timeout(250)
        subito=await pg2.evaluate("""(()=>{const t=document.querySelector('#benvenuto').innerText;return {
          ordine: t.indexOf('Mi ricordo')>=0 && t.indexOf('Mi ricordo')<t.indexOf('scorrendo a destra'), scopri: t.includes('li scopri scorrendo a destra'),
          fissa: getComputedStyle(document.querySelector('.testa')).position==='fixed',
          tocca: document.querySelector('#tocca').offsetParent!==null, d1: document.querySelector('#d1').offsetParent!==null}})()""")
        ok(subito["ordine"] and subito["scopri"], "il saluto: «Mi ricordo di te… nel Profilo» sta sopra «Cosa so già fare lo scopri scorrendo a destra»")
        ok(await pg2.evaluate("(()=>{const y=id=>document.getElementById(id).getBoundingClientRect().top;return y('saluto')<y('ricordo')&&y('ricordo')<y('scopri')&&y('scopri')<y('salto-cosa')})()"), "primo saluto: saluto, «Mi ricordo», «lo scopri scorrendo a destra», «Cosa so fare →»")
        ok(await pg2.inner_text("#avanti-o1")=="Salva" and await pg2.inner_text("#avanti-o2")=="Salva" and await pg2.inner_text("#avanti3")=="Vai avanti", "pulsanti: «Salva», «Salva», «Vai avanti» (JJ, 29/9)")
        ok(not subito["fissa"] and not subito["tocca"] and not subito["d1"], "non compare tutto insieme: prima solo il saluto, la sfera ancora grande")
        await pg2.wait_for_timeout(900)
        ok(await pg2.evaluate("getComputedStyle(document.querySelector('.testa')).position")=="fixed" and not await vede("#tocca"), "poi la sfera e il nome vanno su")
        await pg2.wait_for_timeout(900)
        ok(await vede("#tocca") and not await vede("#d1"), "poi «Adesso imparo te»")
        await pg2.wait_for_timeout(1000)
        ok(await vede("#d1"), "dopo qualche istante «Che lavoro fai?»")
        ok(not await vede("#o2") and not await vede("#o3") and await vede("#benvenuto"), "scelti nome, colore e il mio nome: quei passi spariscono, resta il saluto")
        ok(await pg2.evaluate("getComputedStyle(document.querySelector('.testa')).position")=="fixed", "col saluto la sfera va in alto a sinistra")
        ok(not await vede("#barra-chat") and not await vede("#manda-chat"), "durante il questionario niente casella né Manda della chat")
        await pg2.click('#d1 .scelta >> text=Corriere o autista'); await pg2.wait_for_timeout(300)
        ok(not await vede("#d1") and await vede("#d2") and "interessa davvero" in await pg2.inner_text("#d2"), "risposto «che lavoro fai»: la domanda sparisce, la risposta di Nova apre la seguente")
        ok(not await vede("#tocca"), "anche «Adesso imparo te» se ne va")
        visibili=await pg2.evaluate("[...document.querySelectorAll('#p-inizia .domanda')].filter(x=>x.offsetParent!==null && x.id!=='benvenuto').map(x=>x.id)")
        ok(visibili==["d2"], f"sulla pagina c'è solo la domanda di adesso ({visibili})")
        await pg2.click("#d2 .scelta >> nth=0"); await pg2.click("#avanti2"); await pg2.wait_for_timeout(250)
        ok("interessa davvero" not in await pg2.inner_text("#d3"), "alla domanda del prezzo «Bene. Adesso la parte che mi interessa davvero» non si ripete")
        print("── si riprende da dove ci si era fermati (29 settembre)")
        await pg2.evaluate("(()=>{const r=document.querySelector('#prezzo');r.value=40;r.dispatchEvent(new Event('input'));r.dispatchEvent(new Event('change'))})()")
        await pg2.reload(); await pg2.wait_for_timeout(700)
        vis=await pg2.evaluate("[...document.querySelectorAll('#p-inizia .domanda, #tocca')].filter(x=>x.offsetParent!==null && x.id!=='benvenuto').map(x=>x.id)")
        ok(vis==["d3"], f"ricaricato alla domanda del prezzo: si riapre lì, non da capo ({vis})")
        ok(await pg2.input_value("#prezzo")=="40" and await pg2.inner_text("#valore")=="40", "e il prezzo scelto c'è ancora")
        ok(await pg2.evaluate("document.querySelector('#continua').getAttribute('href')")=="#d3", "«Continuiamo ↓» porta alla domanda di adesso")
        await pg2.click("#avanti3"); await pg2.wait_for_timeout(250)
        await pg2.click("#d5 .scelta >> nth=0"); await pg2.click("#avanti5"); await pg2.wait_for_timeout(250)
        t4=await pg2.inner_text("#d4")
        ok("Come ti chiami" not in t4 and not await pg2.evaluate("document.querySelector('#nome').type!=='hidden'"), "l'ultima domanda non richiede il nome: l'ha già detto all'inizio")
        ok("Parla con" not in t4 and "si apre appena mandi" in t4, "e non rimanda più a «Parla con», che non c'è")
        await pg2.fill("#mail","jacopo@esempio.it"); await pg2.check("#ok"); await pg2.click("#manda"); await pg2.wait_for_timeout(1800)
        inv4=[d for (r,d) in inviati if d.get("mail")=="jacopo@esempio.it"]
        ok(inv4 and inv4[-1].get("nome")=="Jacopo", "con la mail parte il nome detto all'inizio")
        rimaste=await pg2.evaluate("[...document.querySelectorAll('#p-inizia .domanda, #tocca')].filter(x=>x.offsetParent!==null && x.id!=='benvenuto').map(x=>x.id)")
        ok(rimaste==[], f"mandate le risposte, il sondaggio se ne va tutto ({rimaste})")
        ok("Ricevuto" in (await pg2.inner_text("#chat")), "e Nova dice «Ricevuto» nella chat")
        ok(await vede("#barra-chat"), "questionario finito: adesso compare la casella per scrivere")
        await pg2.close()
        print("── i primi passi stanno in uno schermo (29 settembre)")
        for w,h in [(393,740),(360,640)]:
            c3=await b.new_context(viewport={"width":w,"height":h}, is_mobile=True, has_touch=True)
            await c3.route("**/*", instrada); p3=await c3.new_page(); p3.on("pageerror", lambda e: errori.append(str(e)))
            await p3.goto(BASE); await p3.wait_for_timeout(300)
            async def in_vista(sel):
                return await p3.evaluate(f"(()=>{{const n=document.querySelector('.schede').getBoundingClientRect().top,r=document.querySelector('{sel}').getBoundingClientRect();return window.scrollY===0 && r.bottom<=n && r.top>=0}})()")
            await p3.click("#nomi .scelta >> text=Nova"); a1=await in_vista("#avanti-o1")
            await p3.click("#avanti-o1"); await p3.wait_for_timeout(300); await p3.click('.tema[data-tema="naturale"]'); await p3.wait_for_timeout(200); a2=await in_vista("#avanti-o2")
            await p3.click("#avanti-o2"); await p3.wait_for_timeout(300); a3=await in_vista("#salta-o3")
            ok(a1 and a2 and a3, f"{w}x{h}: «Salva», «Salva», «Piacere / Preferisco non dirlo» in vista senza scorrere, con la sfera sopra")
            await c3.close()
        print("── errori JavaScript:", errori or "nessuno")
        ok(not errori, "zero errori in tutta la prova")
        await b.close()
    print(f"\n{'VERDE' if not ok.errori else f'ROSSO: {ok.errori}'}")
asyncio.run(main())
